### ISSUE TITLE
I can't consume kafka messagae at same time. 

### ISSUE THREAD

**Issue by hyeonjae-lee09** [tawk/nestjs-batch-kafka#2]
Thank you for your kafka code. 
I want to consume kafka message only when more than 10 messages have accumulated in Kafka. (or many messages)
In kafkajs, consumer do not wait when kafka message piled up in kafka.
Is this something that can be implemented?

**Comment by AngPuoSyer** [comment]
I believe this is an intended behavior from kafka where the consumer will start consuming the messages once it reaches the `maxWaitTimeInMs` or `minBytes` [threshold](https://kafka.js.org/docs/consuming#a-name-options-a-options). If you are getting only a single message you can try increasing the `maxWaitTimeInMs` or `minBytes` config for your kafka consumer. Regarding about only consuming after a certain amount of messages, as far as I know there is no built-in implementation in kafka to achieve what you intend to do, but you can do it with a simple accumulator pattern in the application layer. Hope this answers your question.

```ts
@Controller()
class AccumulatorBatchController {
  let accumulator = []

 @BatchProcessor('accumulator')
  async processMessages(
      @Payload() data: any[],
      @Ctx() context: KafkaBatchContext,
    ) {
      const heartbeat = context.getHeartbeat();
      const resolveOffset = context.getResolveOffset();
      const commitOffsetsIfNecessary = context.getCommitOffsetsIfNecessary();
  
      await heartbeat();
  
      accumulator.push(...data)

      if(accumulator.length >= 10) {
          // process your data
          // flush accumulator
          accumulator = []
      }

      resolveOffset(context.getMessages().at(-1).offset);
      console.log("Batch resolved");
  
      await heartbeat();
      await commitOffsetsIfNecessary();
    }
}
```

**Comment by hyeonjae-lee09** [comment]
@AngPuoSyer Thank you for your comment.  As you mentioned, I will use `maxWaitTimeInMs` and `minBytes`, `maxBytes`. these method looks good.
